### ISSUE TITLE
Fix pypi github release workflow and add support for python >=3.7, <4

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmecp#21]
* Probably the [PYPI_API_TOKEN](https://github.com/sdss/cluplus/settings/secrets/actions) is missing.
* [Add support for python >3.7 & <4](https://github.com/sdss/lvmecp/blob/c598f9e65d94f379449db2e6541d61e9a6844bdb/pyproject.toml#L35)

**Comment by albireox** [comment]
I'll set `python = "^3.7,<3.11"`. I'm going to merge a major refactor soon, see #20
